#!/bin/sh

. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

        if [ ! -f "/tmp/reset_times" ] ; then
                echo 0 > /tmp/reset_times &
        fi
        reset_times=`cat /tmp/reset_times`
        let reset_times+=1
        echo $reset_times > /tmp/reset_times

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -ge 5 -a -n "$OVERLAY" ]
	then
		echo "FACTORY RESET" > /dev/console
		jffs2reset -y && reboot &
	fi
;;
esac

return 0
