#!/bin/sh /etc/rc.common
START=99
STOP=13
USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "openfi"
}

start_service(){
	if [ -f /var/run/fan_pid ]
	then
		fan_pid=`/var/run/fan_pid`
		kill $fan_pid
	fi

	config_load "openfi"

	procd_open_instance
	procd_set_param command /usr/sbin/op_fan.sh
	procd_set_param respawn
	procd_close_instance

	procd_open_instance
	procd_set_param command /usr/sbin/op_led.sh
	procd_set_param respawn
	procd_close_instance

	/usr/sbin/op_reset_modem.sh
	/usr/sbin/op_switch.sh
}

stop_service(){
	if [ -f /var/run/fan_pid ]
	then
		fan_pid=`/var/run/fan_pid`
		kill $fan_pid
	fi
}

reload_service()
{
	stop
	start
}
